rmdir /s/q %~dp0VSHistory2019\bin 2> \nul
rmdir /s/q %~dp0VSHistory2019\obj 2> \nul
rmdir /s/q %~dp0VSHistory2022\bin 2> \nul
rmdir /s/q %~dp0VSHistory2022\obj 2> \nul
rmdir /s/q %~dp0VSHistoryCT\bin 2> \nul
rmdir /s/q %~dp0VSHistoryCT\obj 2> \nul
rmdir /s/q %~dp0VSHistorySetVersion\bin 2> \nul
rmdir /s/q %~dp0VSHistorySetVersion\obj 2> \nul
rmdir /s/q %~dp0VSTestSettings\bin 2> \nul
rmdir /s/q %~dp0VSTestSettings\obj 2> \nul
