// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSHistory
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSHistory2022.95fbcf1c-4aa4-4c3d-bb67-af0b2792132b";
        public const string Name = "VSHistory 2022 -- Visual Studio File Histories";
        public const string Description = @"VSHistory maintains the history of files in your Visual Studio 2022+ projects every time they are saved.  Any saved version can be viewed or a diff with the current version can be displayed.";
        public const string Language = "en-US";
        public const string Version = "4.0.13";
        public const string Author = "Ken Cross";
        public const string Tags = "File History, File Versions";
        public const bool IsPreview = false;
    }
}
