// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSHistory
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSHistoryWindowPaneString = "902bcf59-0f85-4b8b-9ebd-3ec897906bd2";
        public static Guid VSHistoryWindowPane = new Guid(VSHistoryWindowPaneString);

        public const string VSHistoryString = "02d1238c-021c-479c-938e-ae4d1f89c464";
        public static Guid VSHistory = new Guid(VSHistoryString);

        public const string VSHistoryExtensionsString = "915945ae-3c8a-48d7-a9c3-258ad6bdb845";
        public static Guid VSHistoryExtensions = new Guid(VSHistoryExtensionsString);

        public const string AllFilesString = "1fddebc3-5ae1-4611-9cd0-f12877d82ac1";
        public static Guid AllFiles = new Guid(AllFilesString);

        public const string ExclusionsString = "af70533b-e1fa-452f-a906-de9f1ea32506";
        public static Guid Exclusions = new Guid(ExclusionsString);

        public const string FileLocationString = "3aab6f78-019a-4e16-bbdf-fdc36d1f2d1f";
        public static Guid FileLocation = new Guid(FileLocationString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int VSHistoryCommand = 0x0100;
        public const int VSHistoryAllFiles = 0x0201;
        public const int VSHistory = 0x0203;
        public const int VSHistoryOpen = 0x0204;
        public const int VSHistoryFilter = 0x0205;
        public const int VSHistoryToolbarGroup = 0x1101;
        public const int VSHistoryToolbar = 0x3000;
        public const int VSHistoryExtensionsSettingsID = 0x5102;
        public const int VSHistoryExtensionsToolWindowID = 0x5103;
        public const int ButtonsGroup = 0x5120;
        public const int SubMenuID = 0x5200;
        public const int SubMenuGroupID = 0x5250;
    }
}
